patch api attribute error
the last update of cv2 has introduced API changes that result in error "AttributeError: module 'cv2.aruco' has no attribute 'Dictionary_get'", this commit brings back API compatibility with regards to dictionary and parameters values